/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'option 1 selected' | 'option 2 selected' | 'option 3 selected' | 'mobile v1' | 'mobile v2' | 'mobile v3'
    "click"?: Function
    "click2"?: Function
    "click3"?: Function
}

const ChangelogFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

ChangelogFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default ChangelogFramerComponent

