// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e9385cf9f6db9aa "Alter (copy)", do not edit manually */
"use client";

// virtual:nav/menu-icon
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/aCjnoWQ1NkBR415A8L1a/CE8BQflA1Iz95D884sGk/xQGSOiMYy.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, useActiveVariantCallback, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["Ox_13xhkg", "LRVn1uHTU"];
var serializationHash = "framer-ZkQtd";
var variantClassNames = { LRVn1uHTU: "framer-v-ki2my0", Ox_13xhkg: "framer-v-aplreb" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0 ? void 0 : variants.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { damping: 30, delay: 0, mass: 1, stiffness: 400, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = { Burger: "Ox_13xhkg", X: "LRVn1uHTU" };
var getProps = ({ height, id, tap, width, ...props }) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return { ...props, TBgHLr7MW: tap !== null && tap !== void 0 ? tap : props.TBgHLr7MW, variant: (_ref = (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null && _humanReadableVariantMap_props_variant !== void 0 ? _humanReadableVariantMap_props_variant : props.variant) !== null && _ref !== void 0 ? _ref : "Ox_13xhkg" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, TBgHLr7MW, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "Ox_13xhkg", variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant);
  const onTap1rm7tbn = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (TBgHLr7MW) {
      const res = await TBgHLr7MW(...args);
      if (res === false) return false;
    }
    setVariant("LRVn1uHTU");
  });
  const onTap14zyo4e = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (TBgHLr7MW) {
      const res = await TBgHLr7MW(...args);
      if (res === false) return false;
    }
    setVariant("Ox_13xhkg");
  });
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(serializationHash, ...sharedStyleClassNames, "framer-aplreb", className, classNames), "data-framer-name": "Burger", "data-highlight": true, layoutDependency, layoutId: "Ox_13xhkg", onTap: onTap1rm7tbn, ref: ref !== null && ref !== void 0 ? ref : ref1, style: { ...style }, ...addPropertyOverrides({ LRVn1uHTU: { "data-framer-name": "X", onTap: onTap14zyo4e } }, baseVariant, gestureVariant), children: /* @__PURE__ */ _jsxs(motion.div, { className: "framer-18leysj", "data-framer-name": "hamburger menu", layoutDependency, layoutId: "CP6adHWUD", children: [/* @__PURE__ */ _jsx(motion.div, { className: "framer-vczd68", "data-framer-name": "Bottom", layoutDependency, layoutId: "eqdWZwLMC", style: { backgroundColor: "rgb(0, 0, 0)", rotate: 0 }, variants: { LRVn1uHTU: { rotate: -45 } } }), /* @__PURE__ */ _jsx(motion.div, { className: "framer-ycn294", "data-framer-name": "Mid", layoutDependency, layoutId: "TiX8bufed", style: { backgroundColor: "rgb(0, 0, 0)", opacity: 1 }, variants: { LRVn1uHTU: { opacity: 0 } } }), /* @__PURE__ */ _jsx(motion.div, { className: "framer-1dfkgfw", "data-framer-name": "Top", layoutDependency, layoutId: "ikcxGGvle", style: { backgroundColor: "rgb(0, 0, 0)", rotate: 0 }, variants: { LRVn1uHTU: { rotate: 45 } } })] }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-ZkQtd.framer-1ara51u, .framer-ZkQtd .framer-1ara51u { display: block; }", ".framer-ZkQtd.framer-aplreb { cursor: pointer; height: 32px; overflow: hidden; position: relative; width: 32px; }", ".framer-ZkQtd .framer-18leysj { flex: none; height: 18px; left: calc(50.00000000000002% - 24px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 18px / 2); width: 24px; }", ".framer-ZkQtd .framer-vczd68 { bottom: 0px; flex: none; height: 2px; left: 0px; overflow: hidden; position: absolute; right: 0px; }", ".framer-ZkQtd .framer-ycn294 { flex: none; height: 2px; left: 0px; overflow: hidden; position: absolute; right: 0px; top: calc(50.00000000000002% - 2px / 2); }", ".framer-ZkQtd .framer-1dfkgfw { flex: none; height: 2px; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }", ".framer-ZkQtd.framer-v-ki2my0 .framer-vczd68 { bottom: unset; top: calc(50.00000000000002% - 2px / 2); }", ".framer-ZkQtd.framer-v-ki2my0 .framer-ycn294 { left: unset; width: 2px; }", ".framer-ZkQtd.framer-v-ki2my0 .framer-1dfkgfw { left: unset; right: -1px; top: calc(50.00000000000002% - 2px / 2); width: 26px; }"];
var FramerxQGSOiMYy = withCSS(Component, css, "framer-ZkQtd");
var stdin_default = FramerxQGSOiMYy;
FramerxQGSOiMYy.displayName = "nav / Menu Icon";
FramerxQGSOiMYy.defaultProps = { height: 32, width: 32 };
addPropertyControls(FramerxQGSOiMYy, { variant: { options: ["Ox_13xhkg", "LRVn1uHTU"], optionTitles: ["Burger", "X"], title: "Variant", type: ControlType.Enum }, TBgHLr7MW: { title: "Tap", type: ControlType.EventHandler } });
addFonts(FramerxQGSOiMYy, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:nav/menu-icon
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "LRVn1uHTU",
  "xl": "Ox_13xhkg"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "J986jsEGO": { "path": "/contact" }, "WBTam2e07": { "path": "/404" }, "augiA20Il": { "path": "/" }, "pxZuQniuS": { "path": "/changelog" }, "rQ6ChpM3z": { "path": "/changelog/:slug" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "7e9385cf9f6db9aaff1114dcc78a4c1f2a48c399d43aa1aee82090981b59b32a",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "J986jsEGO": {
          "path": "/contact"
        },
        "WBTam2e07": {
          "path": "/404"
        },
        "augiA20Il": {
          "path": "/"
        },
        "pxZuQniuS": {
          "path": "/changelog"
        },
        "rQ6ChpM3z": {
          "path": "/changelog/:slug"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "7e9385cf9f6db9aaff1114dcc78a4c1f2a48c399d43aa1aee82090981b59b32a",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
